export const bgData = [
    [],
    [require('../../assets/backgrounds/res/BGthrone.png'),require('../../assets/backgrounds/res/restaurant.png'),require('../../assets/backgrounds/res/drinks.png'),require('../../assets/backgrounds/res/party.png'),require('../../assets/backgrounds/res/celebration.png'),require('../../assets/backgrounds/res/food.png'),require('../../assets/backgrounds/res/bday.png'),require('../../assets/backgrounds/res/sport.png')],
    [require('../../assets/backgrounds/res/restaurant.png'),require('../../assets/backgrounds/res/BGthrone.png'),require('../../assets/backgrounds/res/party.png'),require('../../assets/backgrounds/res/drinks.png'),require('../../assets/backgrounds/res/food.png'),require('../../assets/backgrounds/res/celebration.png'),require('../../assets/backgrounds/res/sport.png'),require('../../assets/backgrounds/res/bday.png')],
    [require('../../assets/backgrounds/res/BGthrone.png'),require('../../assets/backgrounds/res/restaurant.png'),require('../../assets/backgrounds/res/drinks.png'),require('../../assets/backgrounds/res/party.png'),require('../../assets/backgrounds/res/celebration.png'),require('../../assets/backgrounds/res/food.png'),require('../../assets/backgrounds/res/bday.png'),require('../../assets/backgrounds/res/sport.png')],
    [require('../../assets/backgrounds/res/restaurant.png'),require('../../assets/backgrounds/res/BGthrone.png'),require('../../assets/backgrounds/res/party.png'),require('../../assets/backgrounds/res/drinks.png'),require('../../assets/backgrounds/res/food.png'),require('../../assets/backgrounds/res/celebration.png'),require('../../assets/backgrounds/res/sport.png'),require('../../assets/backgrounds/res/bday.png')],
    [require('../../assets/backgrounds/res/BGthrone.png'),require('../../assets/backgrounds/res/restaurant.png'),require('../../assets/backgrounds/res/drinks.png'),require('../../assets/backgrounds/res/party.png'),require('../../assets/backgrounds/res/celebration.png'),require('../../assets/backgrounds/res/food.png'),require('../../assets/backgrounds/res/bday.png'),require('../../assets/backgrounds/res/sport.png')],
    [require('../../assets/backgrounds/res/restaurant.png'),require('../../assets/backgrounds/res/BGthrone.png'),require('../../assets/backgrounds/res/party.png'),require('../../assets/backgrounds/res/drinks.png'),require('../../assets/backgrounds/res/food.png'),require('../../assets/backgrounds/res/celebration.png'),require('../../assets/backgrounds/res/sport.png'),require('../../assets/backgrounds/res/bday.png')],
    [require('../../assets/backgrounds/res/BGthrone.png'),require('../../assets/backgrounds/res/restaurant.png'),require('../../assets/backgrounds/res/drinks.png'),require('../../assets/backgrounds/res/party.png'),require('../../assets/backgrounds/res/celebration.png'),require('../../assets/backgrounds/res/food.png'),require('../../assets/backgrounds/res/bday.png'),require('../../assets/backgrounds/res/sport.png')],
]